# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzagSytU85LyIOooqEjHh50vflDfajUA
"""

data = pd.read_csv("results.csv")
data

import pandas as pd

students1 = {
    "ID": [1, 2, 3],
    "Name": ["Amit", "Riya", "Rahul"],
    "Age": [21, 22, 20]
}

students2 = {
    "ID": [4, 5, 6],
    "Name": ["Neha", "Karan", "Priya"],
    "Age": [23, 22, 21]
}

df1 = pd.DataFrame(students1)
df2 = pd.DataFrame(students2)

pd.concat([df1, df2])

marks = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Marks": [85, 90, 78, 78, 97, 78]
}

m_data1 = pd.merge(df1, pd.DataFrame(marks))
m_data2 = pd.merge(df2, pd.DataFrame(marks))

pd.concat([m_data1, m_data2])

pd.merge(df1,df2 , on = 'ID')

pd.merge(df1,df2 , on = 'ID' , how = 'outer')

pd.merge(df1,df2 , on = 'ID' , how = 'inner')

pd.merge(df1,df2 , on = 'ID' , how = 'outer',indicator = True)

pd.merge(df1,df2 , on = 'ID' , how = 'outer',indicator = True.left_index = True, right_index = True)

df1 = pd.DataFrame({
    'User_ID': [101,102,103],
    'Name' : ['Alice','Bob','Charlie']
},index = [11,22,33])

df2 = pd.DataFrame({
    'User_ID': [101,102,104],
    'City' : ['New York','London','Paris']
},index = [100,200,300])

index_access = pd.merge(df1,df2, left_index=True,right_index = True)
index_access

df_21 = pd.DataFrame({
    'User_ID': [101,102,103],
    'Name' : ['Alice','Bob','Charlie']
},index = [11,22,33])

df_22 = pd.DataFrame({
    'User_ID': [101,102,104],
    'City' : ['New York','London','Paris']
},index = [11,22,33])

index_access = pd.merge(df1,df2, left_index=True,right_index = True)
index_access

import numpy as np

data = {
    'Age' : [25, np.nan, 30,22,np.nan],
    'Score' : [85,90,np.nan,75,80],
    'City': ['New York','London',np.nan,'Paris']
}
dataf=pd.DataFrame(data)

print(dataf.isnull())
print(dataf.isnull().sum())

df_clean_rows=dataf.dropna()
df_clean_cols = dataf.dropna(axis = 1)
df_clean_subset = dataf.dropna(subset = ['Age'])

dataf.notnull()

df_zero = dataf.fillna(0)

dataf['Age'] = dataf['Age'].filna(df['Age'].mean())

dataf['City'] = dataf['City'].fillna(df['City'].mode()[0])

df_ffill
df_bfill