# -*- coding: utf-8 -*-
"""list_manipulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEVKGFCn7SJkNlaYj7xPqk_44TZIzcOE
"""

y=x[:]# copy/ range slicing
y=x #copy at same memory
y=x.copy()
x.insert(3,40)  #insert(index,val)
x.count() #checks frequency of val

#how to access list inside list values
x=[1,2,3,[4,5]]
for i in [x[3][1]]:
  print(i)

