# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18msxgFCr-XruVlArnVzMFIHlf-GdFjhO
"""

import matplotlib.pyplot as plt

dir(plt)

days = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
temp = [22,52,62,41,52,52,78,55,58,62,23,24,65,21,24]

#data length should be same or equal
#first is H = x and V = y

plt.plot(days,temp)
plt.title("Rajkot Temp")
plt.xlabel("Days")
plt.ylabel("Temperature")
# plt.show()

#axis
plt.plot(days,temp)
plt.title("Rajkot Temp")
plt.axis([0,20,0,100])   #axis(xmin,xmax,ymin,ymax)
plt.xlabel('days')
plt.ylabel('temp')

plt.plot(days,temp,color = 'm',marker = 'p', linestyle = '-.')
plt.title("Rajkot Temp")
plt.axis([0,20,0,100])   #axis(xmin,xmax,ymin,ymax)
plt.xlabel('days')
plt.ylabel('temp')

plt.plot(days,temp,'yo--')

plt.plot(days,temp,'yo--',linewidth = 2,markersize = 10)

plt.plot(days,temp,'yo--' ,label = "temp line")


plt.title("Rajkot Temp", fontsize = 15)
plt.axis([0,20,0,100])
plt.xlabel('days',fontsize = 12)
plt.ylabel('temp',fontsize = 11)
plt.legend(['temp line'], loc = 10)

plt.plot(days,temp,'yo--' ,label = "temp line")


plt.title("Rajkot Temp", fontsize = 15)
plt.axis([0,20,0,100])
plt.xlabel('days',fontsize = 12)
plt.ylabel('temp',fontsize = 11)
plt.legend( loc = 10)

from matplotlib import style

days = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
m_temp = [22,12,62,42,52,54,18,54,58,62,11,24,65,24,24]
temp = [22,52,62,41,52,52,78,55,58,62,23,24,65,21,24]

plt.plot(days,temp,'gp-',linewidth = 2,markersize = 10, label = "rajkot temp line")
plt.plot(days,m_temp,'yh-',linewidth = 2,markersize = 4, label = "mumbai temp line")

style.use('ggplot')
plt.title("Rajkot Temp", fontsize = 15)
plt.axis([0,20,0,100])
plt.xlabel('days',fontsize = 12)
plt.ylabel('temp',fontsize = 11)
plt.legend(loc = 2)
plt.grid(color = 'm',linestyle = '-.')

"""bar graph

"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import style

classes = ['pyhton','R','AI','ML','DS']
class1_stud = [30,10,20,25,10]
class2_stud = [40,5,20,20,10]
class3_stud = [3,5,30,15,15]

plt.bar(classes, class1_stud)

plt.bar(classes, class2_stud)

plt.barh(classes, class1_stud, color = 'm')

plt.barh(classes, class1_stud, align = 'edge' , color = 'y',
         edgecolor = 'b',linewidth = 2,height = 0.5,alpha = 0.8)

plt.barh(classes, class1_stud, align = 'edge' , color = 'orange',
         edgecolor = 'b',linewidth = 1,height = 0.5,alpha = 0.8, label = 'class1',linestyle = '--')
plt.legend()

plt.bar(classes, class1_stud, align = 'edge' , color = 'y',
         edgecolor = 'b',linewidth = 2,width= 0.5,alpha = 0.8, label = 'class1',hatch = '//',linestyle = '--',visible = True,zorder = 2)

style.use('ggplot')
plt.figure(figsize = (15,9))
plt.bar(classes, class1_stud, align = 'edge' , color = 'y',
         edgecolor = 'b',linewidth = 2,width= 0.5,alpha = 0.8, label = 'class1',hatch = '//',linestyle = '--',visible = True,zorder = 2)
plt.show()

plt.figure(figsize = (15,9))
plt.bar(classes, class1_stud, align = 'edge' , color = 'y',
         edgecolor = 'b',linewidth = 2,width= 0.5,alpha = 0.8, label = 'class1',hatch = '//',linestyle = '--',visible = True,zorder = 2)
plt.title("Bar chart for MU class",fontsize = 10)
plt.xlabel("class",fontsize = 10)
plt.ylabel("no of students",fontsize = 10)

plt.figure(figsize = (10,7))

classes_index = np.arange(len(classes))
width = 0.35
plt.bar(classes_index, class1_stud,width,color = 'y',alpha = 0.8,
         edgecolor = 'g',linewidth = 1,label = "class 1 student")

plt.bar(classes_index + width, class2_stud,width,color = 'orange',alpha = 0.5,
         edgecolor = 'r',linewidth = 1,label = "class 2 student")

plt.title("Bar chart for MU class",fontsize = 10)
plt.xlabel("class",fontsize = 10)
plt.ylabel("no of students",fontsize = 10)
plt.xticks(classes_index,classes)
plt.legend()

plt.figure(figsize = (15,9))
plt.bar(classes, class1_stud, align = 'edge' , color = 'y',
         edgecolor = 'b',linewidth = 2,width= 0.5,alpha = 0.5, label = 'class1',hatch = '//',linestyle = '--',visible = True,zorder = 2)
plt.bar(classes, class2_stud, align = 'edge' , color = 'orange',
        edgecolor = 'b',linewidth = 2,width= 0.5,alpha = 0.5, label = 'class2',hatch = '\\',linestyle = '--',visible = True,zorder = 2)
plt.title("Bar chart for MU class",fontsize = 10)
plt.xlabel("class",fontsize = 10)
plt.ylabel("no of students",fontsize = 10)

plt.figure(figsize = (10,7))

classes_index = np.arange(len(classes))
width = 0.35
plt.bar(classes_index, class1_stud,width,color = 'y',alpha = 0.8,
         edgecolor = 'g',linewidth = 1,label = "class 1 student")

plt.bar(classes_index + width, class2_stud,width,color = 'orange',alpha = 0.5,
         edgecolor = 'r',linewidth = 1,label = "class 2 student")

plt.title("Bar chart for MU class",fontsize = 10)
plt.xlabel("class",fontsize = 10)
plt.ylabel("no of students",fontsize = 10)
plt.xticks(classes_index+width,classes,rotation = 20)
plt.legend()

plt.figure(figsize = (10,7))

classes_index = np.arange(len(classes))
width = 0.35
plt.bar(classes_index, class1_stud,width,color = 'y',alpha = 0.8,
         edgecolor = 'g',linewidth = 1,label = "class 1 student")

plt.bar(classes_index + width, class2_stud,width,color = 'orange',alpha = 0.5,
         edgecolor = 'r',linewidth = 1,label = "class 2 student")

plt.bar(classes_index + width, class3_stud,width,color = 'b',alpha = 0.5,
         edgecolor = 'r',linewidth = 1,label = "class 3 student")

plt.title("Bar chart for MU class",fontsize = 10)
plt.xlabel("class",fontsize = 10)
plt.ylabel("no of students",fontsize = 10)
plt.xticks(classes_index+width,classes,rotation = 90)
plt.legend()

"""pie chart

"""

classes = ['pyhton','R','AI','ML','DS']
class1_stud = [30,10,20,25,10]

plt.pie([1])

plt.pie(class1_stud,labels= classes)

explode = [0.1,0,0,0,0]
plt.pie(class1_stud,labels= classes,explode=explode)

#color = ['r','c','g','y','b']
cmap = plt.cm.Purples
colors = cmap(np.linspace(0,1,len(classes)))
plt.pie(class1_stud,labels= classes,explode=explode,colors = colors)

plt.pie(class1_stud,labels= classes,explode=explode,colors = colors,autopct='%.2f%%',shadow=True)

plt.pie(class1_stud,labels= classes,explode=explode,colors = colors,autopct='%.2f%%',shadow=True,radius=1.4,startangle=90)
plt.show()



textprops = {'fontsize':10,'color' : 'm'}
wedgeprops = {'linewidth':1,'width': 1,'edgecolor':'k'}
plt.pie(class1_stud,
        labels= classes,
        explode=explode,
        colors = colors,
        autopct='%.2f%%',
        shadow=True,
        radius=1,
        startangle=90,
        textprops=textprops,
        pctdistance=0.6,
        labeldistance=1.4,
        counterclock=True,
        wedgeprops=wedgeprops,
        center=(2,3),
        frame=True,
        rotatelabels= False)
plt.show()

"""histogram

"""

import numpy as np
import random

ml_students_age = np.random.randint(18,28,(100))
py_students_age = np.random.randint(14,28,(100)) #start range, end range, (values)

ml_students_age

py_students_age

plt.hist(ml_students_age)
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")

bins = [15,20,25,30,35]
plt.hist(ml_students_age,bins,rwidth=0.70)
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")

bins = [15,20,25,30,35]
plt.hist(ml_students_age,bins,rwidth=0.50,histtype='step') # histtype ='bar', 'barstacked', 'step', 'stepfilled'
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")

plt.hist(ml_students_age,bins,rwidth=0.50,histtype='step',align='left')
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")

plt.hist(ml_students_age,bins,rwidth=0.50,histtype='step',align='left',orientation='horizontal')
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")

plt.hist(ml_students_age,bins,rwidth=0.9,histtype='bar',align='left',color = 'c')
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")

plt.hist(ml_students_age,bins,rwidth=0.9,histtype='bar',align='left',color = 'c',label="ML students")
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")
plt.legend()

plt.hist(ml_students_age,bins,rwidth=0.9,histtype='bar',align='left',color = 'c',label="ML students")
plt.hist(py_students_age,bins,rwidth=0.9,histtype='bar',align='left',color = 'g',label="py students")
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")
plt.legend()

plt.hist([ml_students_age,py_students_age],bins,rwidth=0.8,histtype='bar',align='left',color = ['r','b'],label=["ML students","py students"])
plt.title("ML students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")
plt.legend()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("googleplaystore_updated.csv",nrows=1000)

df

x = df['Rating']
y = df['Reviews']

plt.scatter(x,y)

plt.scatter(x,y,c='g')
plt.title('Google Play Store Apps scatter plot')
plt.xlabel('Rating')
plt.ylabel('Reviews')

plt.scatter(x,y,c='g',marker='*',edgecolors='k',linewidths= 0.4)
plt.title('Google Play Store Apps scatter plot')
plt.xlabel('Rating')
plt.ylabel('Reviews')

plt.figure(figsize = (7,5))
plt.scatter(x,y,c='c',marker='*',edgecolors='b',linewidths= 0.4,s = 200)
plt.title('Google Play Store Apps scatter plot')
plt.xlabel('Rating')
plt.ylabel('Reviews')

plt.figure(figsize = (16,9))
plt.scatter(x,y,c='y',marker='*',edgecolors='b',linewidths= 4,s = 100,alpha=0.5)
plt.scatter(x,df['Installs'],c='y',marker='p',s=80,alpha=0.5,linewidths=5,edgecolors='c')
plt.title('Google Play Store Apps scatter plot')
plt.xlabel('Rating')
plt.ylabel('Reviews')

"""# subplot


"""

plt.subplot()

plt.subplot(2,2,1)

plt.subplot(2,2,1)
plt.subplot(2,2,2)
plt.subplot(2,2,3)
plt.subplot(2,2,4)

plt.subplot(2,2,1)
plt.pie([1])

plt.subplot(2,2,2)
plt.pie([1,2])

plt.subplot(2,2,3)
plt.pie([1,2,3])

plt.subplot(2,2,4)
plt.pie([1,2,3,4])

plt.show()

plt.figure(figsize = (16,9))
plt.subplot(3,2,1)  #row,colums, index
plt.subplot(3,2,2)
plt.subplot(3,2,3)
plt.subplot(3,2,4)
plt.subplot(3,2,5)
plt.subplot(3,2,6)

from matplotlib import style

plt.figure(figsize = (16,9))
plt.subplot(321)
plt.subplot(3,2,1)

days = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
r_temp = [22,52,62,41,52,52,78,55,58,62,23,24,65,21,24]
m_temp = [22,12,62,42,52,54,18,54,58,62,11,24,65,24,24]

plt.plot(days,r_temp,'yo--',linewidth = 0.5,markersize = 4, label = "rajkot_temp")

plt.plot(days,m_temp,'gp-',linewidth = 0.5,markersize = 4, label = "mumbai_temp")

style.use('ggplot')
plt.title("Rajkot Temp", fontsize=16)
plt.axis([0,20,0,50])
plt.xlabel('Days',fontsize=12)
plt.ylabel('Temp',fontsize=12)
plt.legend(loc=8)
plt.grid(color='m',linestyle='-.',linewidth = 0.7)
plt.show()

#--------------------------first plot---------------
import matplotlib.pyplot as plt
from matplotlib import style
import numpy as np


plt.figure(figsize = (16,9))
plt.subplot(321)
plt.subplot(3,2,1)

days = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
r_temp = [22,52,62,41,52,52,78,55,58,62,23,24,65,21,24]
m_temp = [22,12,62,42,52,54,18,54,58,62,11,24,65,24,24]

plt.plot(days,r_temp,'yo--',linewidth = 0.5,markersize = 4, label = "rajkot_temp")

plt.plot(days,m_temp,'gp-',linewidth = 0.5,markersize = 4, label = "mumbai_temp")

style.use('ggplot')
plt.title("Rajkot Temp", fontsize=16)
plt.axis([0,20,0,50])
plt.xlabel('Days',fontsize=12)
plt.ylabel('Temp',fontsize=12)
plt.legend(loc=8)
plt.grid(color='m',linestyle='-.',linewidth = 0.7)
plt.show()

#-------------------------second plot-------------------------------

plt.figure(figsize = (16,9))
plt.subplot(3,2,2)
ML_student_age = np.random.randint(18,45,(100))
DL_student_age = np.random.randint(18,45,(100))
bins = [15,20,25,30,35,40,45]

plt.hist([ML_student_age,DL_student_age],bins,rwidth=0.9,histtype='bar',align='left',orientation='vertical',color = ['c','m'],label=["ML students",'DL students'])

plt.title("ML and DL students age Histogram")
plt.xlabel("Student age category")
plt.ylabel("no of students")
plt.legend()

#-------------------------third plot-------------------------------

plt.figure(figsize = (16,9))
plt.subplot(3,2,3)


categories = ['Apple','Banana','Oranges','Grapes']
store_a_sales = [40,55,35,60]
store_b_sales = [50,45,40,50]

x = np.arange(len(categories))
width= 0.35

plt.bar(x - width/2, store_a_sales,width,label = "Store A",color = 'c')
plt.bar(x + width/2, store_b_sales,width,label = "Store B",color = 'm')

plt.xlabel("Fruits")
plt.ylabel("Sales")
plt.title("Fruits sales comparison")
plt.xticks(x,categories)
plt.legend()

plt.show()

plt.figure(figsize = (16,9))
plt.subplot(3,2,4)

plt.figure(figsize = (16,9))
plt.subplot(3,2,5)

plt.figure(figsize = (16,9))
plt.subplot(3,2,6)
plt.subplot(3,2,6,projection = 'polar',facecolor = 'y',frameon = False)

"""image reading with matplotlib"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread(r"images.jpg")

img

type(img)

img.shape

img.ndim

plt.imshow(img)

plt.axis('off')
plt.imshow(img)
plt.show()

plt.figure(figsize = (15,8))
plt.axis('off')
plt.imshow(img)
plt.colorbar()
plt.show()

plt.figure(figsize = (14,7))
plt.axis('off')
plt.imshow(img,cmap = 'Accent')
plt.colorbar()
plt.show()

plt.figure(figsize = (13,6))
plt.axis('off')
plt.imshow(img,cmap='nipy_spectral')
plt.colorbar()
plt.show()