# -*- coding: utf-8 -*-
"""numpy_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ne1vHB5O1YT03MOWnMvxPx9pVIQl-yqi
"""

import numpy as np

arr_1d = np.array([1,2,3,4])
type(arr_1d)   #datatype

arr_1d.ndim #dimention

arr_1d.size   #size

arr_2d=np.array([[1,2,3],[4,5,6]])  #2d array

arr_2d.ndim

arr_2d.size

arr_2d.shape

arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #3d array

arr_3d.ndim

arr_3d.size

arr_3d.shape

arr_3d.dtype  #gives which type of data is inside

mx_1s = np.ones([5,6])    #ones
print(mx_1s)

mx_1s.ndim

mx_1s.dtype

mx_1s.dtype=("int64")

mx_0s = np.zeros(5, "int64")
print(mx_0s)  #zeros

mx_0s.dtype

mx_0s.dtype=("int64")

mx_0s = np.zeros((3, 5), dtype="int64")
print(mx_0s)  #zeros

mx_0s.ndim

arr1 = np.arange(1,8)
print(arr1)

np.linspace(1,3,6)   #gives list of values from first val to last val with size of third param

arr_3d.ravel()
print(arr_3d)

arr_2d.flatten('f')

arr_2d.transpose()

metrix1 = np.matrix(([1,2,3],[4,5,6],[7,8,9]),"int64")
print(metrix1)

metrix2 = np.matrix(([11,22,33],[44,55,66],[77,88,99]),"int64")
print(metrix2)

h_stack = np.hstack((metrix1,metrix2))
print(stack)

v_stack = np.vstack((metrix1,metrix2))
print(v_stack)

"""math functions"""

np.add(metrix1,metrix2)
print(metrix1+metrix2)

np.subtract(metrix1,metrix2)
print(metrix1-metrix2)

np.multiply(metrix1,metrix2)
print(metrix1*metrix2)

np.divide(metrix1,metrix2)
print(metrix1/metrix2)

print(metrix1@metrix2) #product

np.min(metrix1)          #min of metrix
np.min(metrix1,axis=0)     #min of axis x

np.min(metrix2)   #min of metrix
np.min(metrix2,axis=1)   #min of y axis

np.max(metrix1)               #max of metrix
np.max(metrix1,axis=0)          #max of x axis

np.max(metrix2)               #max of metrix
np.max(metrix2,axis=1)          #max of y axis

"""series

"""

import pandas as pd

data = [10,20,30,40,50]
lab = ['j','e','n','s','i']

s = pd.Series(data,index = lab)
print(s)

s2 = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
print(s2)

data1 = [[10,20,30],[10,20,40]]
s3 = pd.Series(data1)
print(s3)

print(type(s3))

print(s3.size)

print(s3[1][2])

"""dataframe"""

df = pd.DataFrame(data1,columns=['A','B','C'],index=['a','b'])
print(type(df))
df

data2 = [('raj',89),('sej',23),('alex',32)]
d = pd.DataFrame(data2,columns=['Name','Marks'])
print(d)

d

data3 = {
    'roll' : [1,2,3,4,5],
    'name' : ['radha','krish','shyam','murli','yashodha']
}

df2 = pd.DataFrame(data3)
df2

nested_list = [['swaraj',10],['raj',20],['jay',21],['sase',23]]
data4 = pd.DataFrame(nested_list,columns=['Name','Age'])
data4

import numpy as np

d1 = np.array([1,2,3,4])
d2 = np.array([5,6,7,8])

Data_fr = {
    'df1' : d1,
    'df2' : d2
}
print(Data_fr)

from google.colab import files
upload = files.upload()

#reading data
df = pd.read_csv('IPL2025Bowlers.csv')

#exploring data

print(df.head)

print(df.tail)

print(df.columns)

print(df.dtypes)

print(df.info())

print(df.describe())

print(df.size)

print(df.shape)

df.dropna()

df.fillna(1,inplace=True)

"""selecting data"""

print(df.columns)

print(df[['BBI','AVG']])

#convert types of columns

df['OVR'].astype('float64')

"""sorting data"""

df.sort_values('Player Name',ascending=False)     #str sorting

df.sort_values('WKT')  #int sorting

df.rename({'MAT' :'MATCH'})

import pandas as pd
df = pd.read_csv('student_results.xls')
df

df.iloc[:]

df.loc[0]

df.loc[1]

df.loc[[0,1,2,3]]

df.loc[4,'Class']

df.loc[0:2,'Percantege']

df.loc[df['Class']<11]

df.loc[df['Class']<11,['Percantege']]

df.loc[df['Class']>10,['Study hrs']]

df.iloc[0]

df.iloc[[0]]

df.iloc[:0]

