# -*- coding: utf-8 -*-
"""numpy_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etQ4rxEAGHhXN2jHCTTOjaSWwihNukAZ
"""

import numpy as np
var1 = "jensi"
var2 = "hello python"
var3 = [1,2,3,4,5]

dir(np)

var1.upper()
var1.capitalize()

np.char.upper(var1)

np.char.count(var2,"l")

np.char.center(var1,20,"*")

np.char.index(var2,"llo")

np.char.capitalize(var2)

np.char.equal(var2,var1)

np.char.find(var1,"o")

np.char.compare_chararrays(var1,var2,'>=',True)

np.char.replace(var1,'jensi','jency')

np.char.rstrip(var2,'n')



np.abs(var3)

np.sum(var3)

np.insert(var3,5,8)

var4= [6,7,8,9,10]

np.add(var3,var4)



np.min(var4)

np.mean(var4)

import numpy as np

arr_1d = np.array([1,2,3,4])
type(arr_1d)   #datatype

arr_1d.size   #size

arr_1d.ndim #dimention

arr_2d=np.array([[1,2,3],[4,5,6]])  #2d array