# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGoeaLo1qBO1yEHcRn4EZx_b4QYTZczu
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

sns.get_dataset_names()

titanic = sns.load_dataset('titanic')
print(titanic.head(10))

titanic['survived'].value_counts()

titanic['sex'].value_counts()

titanic['age'].sort_values()

titanic.isnull().sum()

titanic.duplicated().sum()

titanic['age'].fillna(titanic['age'].mean())

titanic.drop('deck', axis=1, inplace=True)

titanic.describe()

((titanic['survived'] ==1 ) & (titanic['sex'] == 'female')) .value_counts()

titanic['survived'].value_counts()

((titanic['survived'] ==1 ) & (titanic['sex'] == 'male')) .value_counts()

import seaborn as sns

sns.displot(titanic['age'])

titanic.columns

sns.histplot(titanic['age'])

days = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
r_temp = [22,52,62,41,52,52,78,55,58,62,23,24,65,21,24]
m_temp = [22,12,62,42,52,54,18,54,58,62,11,24,65,24,24]

sns.lineplot(x=days, y=r_temp, color='red')

df = pd.DataFrame({'days':days, 'r_temp':r_temp})

"""# lineplot"""

sns.lineplot(x= 'days',y= 'r_temp',data=df)

sns.lineplot(x= df['days'],y= df['r_temp'],data=df)

tips_df = sns.load_dataset('tips')

tips_df
tips_df.dtypes

sns.lineplot(x='total_bill', y='tip', data=tips_df)

tips_df.columns

sns.lineplot(x='total_bill', y='tip', data=tips_df)
sns.lineplot(x = 'total_bill',y='sex',data=tips_df)

sns.lineplot(x='size',y='total_bill',data=tips_df,hue='smoker',style='smoker')

sns.lineplot(x='size',y='total_bill',data=tips_df,hue='smoker',style='smoker',palette='hot')

sns.lineplot(x='size',y='total_bill',data=tips_df,hue='smoker',style='smoker',palette='hot',dashes= False)

sns.lineplot(x='size',
             y='total_bill',
             data=tips_df,
             hue='smoker',
             style='smoker',
             palette='hot',
             dashes= False,
             markers=['o','<'],
             legend = False)

sns.lineplot(x='size',
             y='total_bill',
             data=tips_df,
             hue='smoker',
             style='smoker',
             palette='hot',
             dashes= False,
             markers=['o','<'],
             legend = 'brief')

plt.figure(figsize=(16,9))
sns.set(style='darkgrid')
sns.lineplot(x='size',
             y='total_bill',
             data=tips_df,
             hue='day',
             style='day',
             palette='hot',
             dashes= False,
             markers=['o','<','>','^'],
             legend = 'brief')

plt.title('line plot',fontsize=20)
plt.xlabel('size',fontsize=14)
plt.ylabel('total_bill',fontsize=14)
plt.show()

"""# histplot"""

sns.histplot(tips_df['total_bill'])

"""# distplot"""

sns.distplot(tips_df['total_bill'],hist=False)

sns.distplot(tips_df['total_bill'],hist=True)

sns.distplot(tips_df['total_bill'],kde = False)

sns.distplot(tips_df['total_bill'],rug = True)

